// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pkxiikkcbqsrztlizcbo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBreGlpa2tjYnFzcnp0bGl6Y2JvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyMTk0ODksImV4cCI6MjA2Njc5NTQ4OX0.triW6E_aSgaOFK_I3v4pO11r7mNyfhNOPGip4aRV1WE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);